### ISSUE TITLE
Launch site?

### ISSUE THREAD

**Issue by Jaknil** [KubenKoder/web#5]
Ner ska vi kobble kubenkoder.no till sidans innehåll?

Nå så viser kubenkoder.no dette: "www.kubenkoder.no er registrert, men har ingen aktiv nettside ennå."

**Comment by junlarsen** [comment]
Vet vi hvem som eier domenet og har vi en server? Det er parket til 185.134.245.113 akkurat nå, men ved å sjekke hvem som eier 185.134.245.113 ser vi fort at det er parket til nameserveren til en domain registrar. 

Vi må finne ut hvem som eier domenet og få dem til å pointe det til en server.
